<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class EquipaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('equipas')->insert([
            [
                'nome' => 'Tubarões do Rio',
                'modalidade' => 'Futebol',
                'categoria' => 'Sénior',
                'ano_fundacao' => 2010,
                'logo_url' => 'http://example.com/logos/equipa1.png',
                'local_treino' => 'Campo da Cidade',
                'local_jogo' => 'Estádio Municipal',
                'descricao' => 'Equipa principal de futebol, campeã em 2024.',
                'clube_id' => 1,
                'created_by' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nome' => 'Basquetebolistas da Praia',
                'modalidade' => 'Basquetebol',
                'categoria' => 'Sub-20',
                'ano_fundacao' => 2018,
                'logo_url' => 'http://example.com/logos/equipa2.png',
                'local_treino' => 'Pavilhão 2',
                'local_jogo' => 'Pavilhão Principal',
                'descricao' => 'Equipa jovem de basquetebol.',
                'clube_id' => 1,
                'created_by' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nome' => 'Equipa Vencedora',
                'modalidade' => 'Voleibol',
                'categoria' => 'Sénior',
                'ano_fundacao' => 2005,
                'logo_url' => 'http://example.com/logos/equipa3.png',
                'local_treino' => 'Ginásio Central',
                'local_jogo' => 'Pavilhão do Clube',
                'descricao' => 'Equipa feminina de voleibol.',
                'clube_id' => 2,
                'created_by' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nome' => 'Águias Douradas',
                'modalidade' => 'Futebol',
                'categoria' => 'Sub-17',
                'ano_fundacao' => 2015,
                'logo_url' => 'http://example.com/logos/equipa4.png',
                'local_treino' => 'Campo Auxiliar',
                'local_jogo' => 'Estádio Municipal',
                'descricao' => 'Equipa de formação juvenil com foco no desenvolvimento de talentos.',
                'clube_id' => 1,
                'created_by' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nome' => 'Leões do Norte',
                'modalidade' => 'Futebol',
                'categoria' => 'Sub-15',
                'ano_fundacao' => 2016,
                'logo_url' => 'http://example.com/logos/equipa5.png',
                'local_treino' => 'Campo de Treinos B',
                'local_jogo' => 'Campo Secundário',
                'descricao' => 'Equipa de iniciados com grande potencial.',
                'clube_id' => 2,
                'created_by' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nome' => 'Tigres Brancos',
                'modalidade' => 'Futsal',
                'categoria' => 'Sénior',
                'ano_fundacao' => 2012,
                'logo_url' => 'http://example.com/logos/equipa6.png',
                'local_treino' => 'Pavilhão Desportivo',
                'local_jogo' => 'Pavilhão Municipal',
                'descricao' => 'Equipa de futsal masculino, vice-campeã regional.',
                'clube_id' => 1,
                'created_by' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nome' => 'Panteras Negras',
                'modalidade' => 'Basquetebol',
                'categoria' => 'Sénior',
                'ano_fundacao' => 2008,
                'logo_url' => 'http://example.com/logos/equipa7.png',
                'local_treino' => 'Pavilhão 1',
                'local_jogo' => 'Arena Central',
                'descricao' => 'Equipa sénior masculina de basquetebol.',
                'clube_id' => 2,
                'created_by' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nome' => 'Falcões Azuis',
                'modalidade' => 'Andebol',
                'categoria' => 'Sénior',
                'ano_fundacao' => 2011,
                'logo_url' => 'http://example.com/logos/equipa8.png',
                'local_treino' => 'Pavilhão 3',
                'local_jogo' => 'Pavilhão Principal',
                'descricao' => 'Equipa de andebol com tradição em competições nacionais.',
                'clube_id' => 1,
                'created_by' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nome' => 'Guerreiras do Sul',
                'modalidade' => 'Voleibol',
                'categoria' => 'Sub-18',
                'ano_fundacao' => 2019,
                'logo_url' => 'http://example.com/logos/equipa9.png',
                'local_treino' => 'Ginásio B',
                'local_jogo' => 'Pavilhão do Clube',
                'descricao' => 'Equipa feminina juvenil de voleibol.',
                'clube_id' => 2,
                'created_by' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nome' => 'Relâmpagos',
                'modalidade' => 'Atletismo',
                'categoria' => 'Misto',
                'ano_fundacao' => 2007,
                'logo_url' => 'http://example.com/logos/equipa10.png',
                'local_treino' => 'Pista de Atletismo',
                'local_jogo' => 'Estádio de Atletismo',
                'descricao' => 'Equipa de atletismo com atletas de várias categorias.',
                'clube_id' => 1,
                'created_by' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nome' => 'Dragões Vermelhos',
                'modalidade' => 'Futebol',
                'categoria' => 'Sub-13',
                'ano_fundacao' => 2020,
                'logo_url' => 'http://example.com/logos/equipa11.png',
                'local_treino' => 'Campo de Treinos C',
                'local_jogo' => 'Campo Secundário',
                'descricao' => 'Equipa de benjamins em fase de crescimento.',
                'clube_id' => 2,
                'created_by' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nome' => 'Cobras Verdes',
                'modalidade' => 'Ténis de Mesa',
                'categoria' => 'Sénior',
                'ano_fundacao' => 2014,
                'logo_url' => 'http://example.com/logos/equipa12.png',
                'local_treino' => 'Sala de Ténis de Mesa',
                'local_jogo' => 'Pavilhão Multiusos',
                'descricao' => 'Equipa de ténis de mesa com participação em torneios regionais.',
                'clube_id' => 1,
                'created_by' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);
    }
}
